-- MySQL Script generated by MySQL Workbench
-- Mon May  4 15:28:14 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Book`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Book` (
  `도서번호` INT NOT NULL,
  `출판사이름` VARCHAR(18) NOT NULL,
  `도서이름` VARCHAR(45) NULL,
  `도서단가` INT NULL,
  PRIMARY KEY (`도서번호`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Publisher`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Publisher` (
  `출판사이름` VARCHAR(18) NOT NULL,
  `담당자이름` VARCHAR(45) NULL,
  `전화번호` VARCHAR(12) NULL,
  `도서_도서번호` INT NOT NULL,
  PRIMARY KEY (`출판사이름`),
  INDEX `fk_출판사_도서_idx` (`도서_도서번호` ASC) VISIBLE,
  CONSTRAINT `fk_출판사_도서`
    FOREIGN KEY (`도서_도서번호`)
    REFERENCES `mydb`.`Book` (`도서번호`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
